apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: database
  replicas: 3
  serviceName: deployment-test
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database-container
        image: ubuntu
        imagePullPolicy: IfNotPresent
        command:
          - "sleep"
          - "604800"
        volumeMounts: 
        - name: database-volume
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: database-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: longhorn
      resources:
        requests:
          storage: 1Gi